In [1]:
import polymv

Let's create a test set of $a_{\ell m}$s:

In [2]:
polymv.np.random.seed(1)
alm = polymv.hp.synalm(polymv.np.ones(2000), lmax=1500)
alm

array([ 1.62434536+0.j        , -0.61175641+0.j        ,
       -0.52817175+0.j        , ...,  0.46115612+0.59244991j,
        0.35090859+1.18446272j, -0.5622994 -0.69337834j])

# `polymv.mvs`

To obtain multipole vectors:

In [3]:
help(polymv.mvs.m_vectors)

Help on function m_vectors in module polymv:

m_vectors(alms, l)
    Get multipole vectors in spherical coordinates for a multipole given a map.
    
    Args:
        alms (complex array): multipole moments from a map (Healpy indexing).
        l (int): multipole.
    
    Returns:
        Float array [theta, phi] in radians.



Let's extract the multipole vectors for $\ell=1500$:

In [4]:
mvs_1500 = polymv.mvs.m_vectors(alm, 1500)
mvs_1500.shape, mvs_1500

((3000, 2),
 array([[ 3.01062304,  1.1866423 ],
        [ 3.09263842,  0.21240479],
        [ 3.0758707 ,  1.94877701],
        ...,
        [ 0.07286444,  2.06658143],
        [ 0.04895423, -2.92918786],
        [ 0.01967822,  0.48225845]]))

To extract the multiple multipole vectors for a range or a list of multipoles, let's say from $\ell=2$ to $\ell=5$:

In [5]:
help(polymv.mvs.many_m_vectors)

Help on function many_m_vectors in module polymv:

many_m_vectors(alm, multipoles, parallel=4)
    Get several multipole vectors in spherical coordinates.
    
    Args:
        alms (complex array): multipolar coefficients from a map.
        multipoles (list, or range): list or range of multipoles.
        parallel (int): number of parallel process.
    
    Returns:
        Float array [multipole, [theta, phi]] in radians.



In [6]:
polymv.mvs.many_m_vectors(alm, range(2, 5 + 1))

array([[ 1.83441666,  0.12767786],
       [ 1.37302603,  1.33828394],
       [ 1.30717599, -3.01391479],
       [ 1.76856662, -1.80330872],
       [ 2.73836992,  2.08191869],
       [ 1.52087956,  0.19300013],
       [ 1.62071309, -2.94859252],
       [ 2.34022757,  0.13144151],
       [ 0.40322273, -1.05967396],
       [ 0.80136509, -3.01015115],
       [ 2.67239211,  2.6970591 ],
       [ 2.72904397, -0.04693826],
       [ 1.68134191, -1.61594698],
       [ 1.92945378, -0.50881857],
       [ 1.46025074,  1.52564568],
       [ 1.21213887,  2.63277408],
       [ 0.46920054, -0.44453355],
       [ 0.41254869,  3.09465439],
       [ 1.88305141, -3.08268267],
       [ 2.0002518 , -1.95979302],
       [ 2.39314475, -0.68251023],
       [ 1.80531117,  0.80260215],
       [ 2.58851484,  1.73458048],
       [ 1.25854124,  0.05890998],
       [ 1.14134086,  1.18179963],
       [ 0.7484479 ,  2.45908243],
       [ 1.33628148, -2.33899051],
       [ 0.55307782, -1.40701218]])

In [7]:
mvs_2_to_5 = polymv.mvs.many_m_vectors(alm, [2, 3, 4, 5])
mvs_2_to_5

array([[ 1.83441666,  0.12767786],
       [ 1.37302603,  1.33828394],
       [ 1.30717599, -3.01391479],
       [ 1.76856662, -1.80330872],
       [ 2.73836992,  2.08191869],
       [ 1.52087956,  0.19300013],
       [ 1.62071309, -2.94859252],
       [ 2.34022757,  0.13144151],
       [ 0.40322273, -1.05967396],
       [ 0.80136509, -3.01015115],
       [ 2.67239211,  2.6970591 ],
       [ 2.72904397, -0.04693826],
       [ 1.68134191, -1.61594698],
       [ 1.92945378, -0.50881857],
       [ 1.46025074,  1.52564568],
       [ 1.21213887,  2.63277408],
       [ 0.46920054, -0.44453355],
       [ 0.41254869,  3.09465439],
       [ 1.88305141, -3.08268267],
       [ 2.0002518 , -1.95979302],
       [ 2.39314475, -0.68251023],
       [ 1.80531117,  0.80260215],
       [ 2.58851484,  1.73458048],
       [ 1.25854124,  0.05890998],
       [ 1.14134086,  1.18179963],
       [ 0.7484479 ,  2.45908243],
       [ 1.33628148, -2.33899051],
       [ 0.55307782, -1.40701218]])

# `polymv.otherfuncs`

In [8]:
help(polymv.otherfuncs.get_multipole)

Help on function get_multipole in module polymv:

get_multipole(alms, l)
    Get specific multipolar coefficients.
    
    Args:
        alms (complex array): multipolar coefficients.
        l (int): multipole.
    
    Returns:
        Complex array.



In [9]:
polymv.otherfuncs.get_multipole(alm, 2)

array([-0.52817175+0.j        , -0.19178766-0.33300332j,
        0.14695466-1.39663815j])

Extract specific multipole vectors from many others:

In [10]:
polymv.otherfuncs.get_mvs_from_many(mvs_2_to_5, 2, 5, 2)

array([[ 1.83441666,  0.12767786],
       [ 1.37302603,  1.33828394],
       [ 1.30717599, -3.01391479],
       [ 1.76856662, -1.80330872]])

In [11]:
polymv.otherfuncs.get_mvs_from_many(mvs_2_to_5, 2, 5, 5)

array([[ 1.88305141, -3.08268267],
       [ 2.0002518 , -1.95979302],
       [ 2.39314475, -0.68251023],
       [ 1.80531117,  0.80260215],
       [ 2.58851484,  1.73458048],
       [ 1.25854124,  0.05890998],
       [ 1.14134086,  1.18179963],
       [ 0.7484479 ,  2.45908243],
       [ 1.33628148, -2.33899051],
       [ 0.55307782, -1.40701218]])

Multipole vectors in Cartesian coordinates:

In [12]:
help(polymv.otherfuncs.to_cart)

Help on function to_cart in module polymv:

to_cart(theta_phi_array)
    Convert spherical to Cartesian coordinate. This function works only for a single multipole or stacked arrays, e.g. 2 and 3 MVs together.
    
    Args:
        theta_phi_array (float array): array containing in radians [theta, phi].
    
    Returns:
        Float array.



In [13]:
polymv.otherfuncs.to_cart(mvs_1500)

array([[ 0.04894393,  0.12107717, -0.99143573],
       [ 0.04783496,  0.01031598, -0.99880198],
       [-0.02423687,  0.06103879, -0.99784109],
       ...,
       [-0.03463258,  0.06403453,  0.99734656],
       [-0.04783496, -0.01031598,  0.99880198],
       [ 0.01743279,  0.0091258 ,  0.99980639]])

same task for a list of multiple multipole vectors:

In [14]:
polymv.otherfuncs.to_cart(mvs_2_to_5)

array([[ 0.95759438,  0.12293233, -0.26057752],
       [ 0.22593142,  0.95412221,  0.19648358],
       [-0.95759438, -0.12293233,  0.26057752],
       [-0.22593142, -0.95412221, -0.19648358],
       [-0.19193749,  0.34223634, -0.91980122],
       [ 0.98021076,  0.19156527,  0.04989604],
       [-0.98021076, -0.19156527, -0.04989604],
       [ 0.71211037,  0.09414366, -0.69572681],
       [ 0.19193749, -0.34223634,  0.91980122],
       [-0.71211037, -0.09414366,  0.69572681],
       [-0.40822725,  0.19445119, -0.89193007],
       [ 0.40050388, -0.01881277, -0.91610192],
       [-0.04485981, -0.99288316, -0.11032057],
       [ 0.81775031, -0.45614821, -0.35101743],
       [ 0.04485981,  0.99288316,  0.11032057],
       [-0.81775031,  0.45614821,  0.35101743],
       [ 0.40822725, -0.19445119,  0.89193007],
       [-0.40050388,  0.01881277,  0.91610192],
       [-0.94999241, -0.05602886, -0.30720545],
       [-0.34482062, -0.84126687, -0.41637578],
       [ 0.52806423, -0.429222  , -0.732

Obtain multipole vectors on north hemisphere:

In [15]:
help(polymv.otherfuncs.mvs_north)

Help on function mvs_north in module polymv:

mvs_north(mvs)
    Get multipole vectors on north hemisphere.
    
    Args:
        mvs (float array): array containing multipole vectors [theta, phi].
    
    Returns:
        Float array [theta, phi] in radians.



In [16]:
mvs_1500.shape

(3000, 2)

In [17]:
polymv.otherfuncs.mvs_north(mvs_1500).shape, polymv.otherfuncs.mvs_north(mvs_1500)

((1500, 2),
 array([[ 0.59838197, -1.51504829],
        [ 1.40210428, -2.77471295],
        [ 0.84922632,  2.16353699],
        ...,
        [ 0.07286444,  2.06658143],
        [ 0.04895423, -2.92918786],
        [ 0.01967822,  0.48225845]]))

In [18]:
help(polymv.otherfuncs.many_mvs_north)

Help on function many_mvs_north in module polymv:

many_mvs_north(mvs, lin, lout)
    Get multipole vectors on north hemisphere for multiples multipoles.
    
    Args:
        mvs (float array): array containing multipole vectors [theta, phi].
        lin (int): initial multipole.
        lout (int): final multipole.
    
    Returns:
        Float array [theta, phi] in radians.



In [19]:
polymv.otherfuncs.many_mvs_north(mvs_2_to_5, 2, 5)

array([[ 1.37302603,  1.33828394],
       [ 1.30717599, -3.01391479],
       [ 1.52087956,  0.19300013],
       [ 0.40322273, -1.05967396],
       [ 0.80136509, -3.01015115],
       [ 1.46025074,  1.52564568],
       [ 1.21213887,  2.63277408],
       [ 0.46920054, -0.44453355],
       [ 0.41254869,  3.09465439],
       [ 1.25854124,  0.05890998],
       [ 1.14134086,  1.18179963],
       [ 0.7484479 ,  2.45908243],
       [ 1.33628148, -2.33899051],
       [ 0.55307782, -1.40701218]])

# `polymv.fvs`:

In [20]:
help(polymv.fvs.psi)

Help on function psi in module polymv:

psi(mvs, type_='min')
    Fréchet Mean maximum or minimum.
    
    Args:
        mvs (float array): multipole vectors from an specific multipole.
    
    Returns:
        A vector.



In [21]:
polymv.fvs.psi(mvs_1500)

array([8.80389499e+03, 6.48388889e-01, 2.74348720e+00])

In [22]:
polymv.fvs.psi(mvs_1500, type_='max')

array([8.80517528e+03, 1.25981863e+00, 1.34223319e-01])