Tested on a DELL XPS 8900 with 6th Generation Intel® Core™ i5-6400 Processor (2.7 GHz up to 3.3 GHz, 6MB Cache)

In [1]:
import numpy as np
import healpy as hp

from polymv import polymv

In [2]:
help(polymv)

Help on module polymv.polymv in polymv:

NAME
    polymv.polymv

FUNCTIONS
    frechet_single(theta, phi)
        Compute a single Fréchet vector for an arbitrary set of polar unit vectors.
        Parameters:
            theta: polar angles in radians
            phi:   azimuthal angles in radians
        Returns:
            (out_theta, out_phi): scalar floats
    
    fvs(input1, input2, LMAX)
        Get Fréchet mean vectors in spherical coordinates for a multipole given a map based on lmax.
        
        Parameters:
            input1 (float): Multipole vector theta coordinate.
            input2 (float): Multipole vector phi coordinate.
            LMAX (int): Maximum l value to compute the Fréchet mean.
        
        Returns:
            array: An array for all Fréchet mean based on all multipole vectors in spherical coordinates (theta, phi) from l=2 to lmax.
    
    mvs(input1, input2, LMAX)
        Get multipole vectors in spherical coordinates for a multipole given a m

In [3]:
lmax = 1000

In [4]:
%%time
np.random.seed(1)
alm = hp.synalm(np.ones(2000), lmax=lmax)
alm = np.column_stack([alm.real, alm.imag])
alm

CPU times: user 117 ms, sys: 60.4 ms, total: 177 ms
Wall time: 188 ms


array([[ 1.62434536,  0.        ],
       [-0.61175641,  0.        ],
       [-0.52817175,  0.        ],
       ...,
       [ 1.11714916, -0.99488594],
       [-0.6086487 , -0.1979553 ],
       [-0.30078779, -0.7546471 ]], shape=(501501, 2))

In [5]:
%%time
mvs = polymv.mvs(alm[:, 0], alm[:, 1], lmax)
mvs

CPU times: user 9min 51s, sys: 8.16 s, total: 10min
Wall time: 1min 58s


(array([1.44757865, 1.13235582, 1.694014  , ..., 0.13904038, 0.03596525,
        0.02547674], shape=(1000998,)),
 array([-0.23422314,  1.99653803,  2.90736952, ..., -0.67228949,
         0.58064643,  3.01546658], shape=(1000998,)))

In [6]:
%%time
fvs = polymv.fvs(mvs[0], mvs[1], lmax)
fvs

CPU times: user 1min 32s, sys: 121 ms, total: 1min 32s
Wall time: 24.4 s


(array([0.61115976, 1.18988717, 1.32016361, 1.56128963, 0.3543463 ,
        0.45480577, 0.94377425, 1.04494455, 1.52727431, 0.18051245,
        1.52732415, 0.96149184, 1.37363869, 1.17209017, 0.464179  ,
        0.28098361, 0.36795363, 0.73498171, 1.1783121 , 0.93807245,
        0.62122026, 0.740094  , 0.37658433, 1.1288879 , 1.34351662,
        1.51239635, 0.406846  , 1.09398758, 0.31940905, 1.16675205,
        1.42418699, 0.34544435, 1.01585885, 1.34502284, 1.13699466,
        1.48060661, 0.52546524, 1.02634974, 1.43936494, 0.55857834,
        1.20917053, 1.08943232, 1.18558522, 0.95940178, 0.37270397,
        0.35666326, 0.45447255, 1.29522064, 0.73680289, 1.06716336,
        1.16739385, 1.53766725, 1.1479836 , 0.93937676, 0.70713515,
        1.5180587 , 0.77274462, 0.876563  , 1.43312018, 1.09944856,
        0.50418795, 1.31873667, 1.15597321, 0.67163328, 1.04976079,
        0.28498583, 0.82622091, 1.46959695, 1.46224282, 1.42683723,
        1.25008754, 0.63986768, 0.71239603, 1.06

In [7]:
%%time
fvs_single = polymv.frechet_single(fvs[0], fvs[1])
fvs_single

CPU times: user 266 ms, sys: 1.89 ms, total: 268 ms
Wall time: 283 ms


(0.029493158924209985, 2.4531159345735434)