Tested on a DELL XPS 8900 with 6th Generation Intel® Core™ i5-6400 Processor (2.7 GHz up to 3.3 GHz, 6MB Cache)

In [ ]:
import numpy as np
import healpy as hp

from polymv import polymv

In [2]:
help(polymv)

Help on module polymv.polymv in polymv:

NAME
    polymv.polymv

FUNCTIONS
    fvs(input1, input2, LMAX)
        Get Fréchet mean vectors in spherical coordinates for a multipole given a map based on lmax.

        Parameters:
            input1 (float): Multipole vector theta coordinate.
            input2 (float): Multipole vector phi coordinate.
            LMAX (int): Maximum l value to compute the Fréchet mean.

        Returns:
            array: An array for all Fréchet mean based on all multipole vectors in spherical coordinates (theta, phi) from l=2 to lmax.

    mvs(input1, input2, LMAX)
        Get multipole vectors in spherical coordinates for a multipole given a map based on lmax.

        Parameters:
            input1 (float): Real part of multipole moments from a map (Healpy indexing).
            input2 (float): Imaginary part of multipole moments from a map (Healpy indexing).
            LMAX (int): Maximum l value to compute the multipole vectors.

        Returns:
 

In [3]:
lmax = 1000

In [4]:
%%time
np.random.seed(1)
alm = hp.synalm(np.ones(2000), lmax=lmax)
alm = np.column_stack([alm.real, alm.imag])
alm

CPU times: user 43 ms, sys: 11.8 ms, total: 54.8 ms
Wall time: 54.3 ms


array([[ 1.62434536,  0.        ],
       [-0.61175641,  0.        ],
       [-0.52817175,  0.        ],
       ...,
       [ 1.11714916, -0.99488594],
       [-0.6086487 , -0.1979553 ],
       [-0.30078779, -0.7546471 ]], shape=(501501, 2))

In [5]:
%%time
mvs = polymv.mvs(alm[:, 0], alm[:, 1], lmax)
mvs

CPU times: user 5min 50s, sys: 3.91 s, total: 5min 53s
Wall time: 1min 37s


(array([1.44757865, 1.13235582, 1.694014  , ..., 0.13904038, 0.03596525,
        0.02547674], shape=(1000998,)),
 array([-0.23422314,  1.99653803,  2.90736952, ..., -0.67228949,
         0.58064643,  3.01546658], shape=(1000998,)))

In [6]:
%%time
fvs = polymv.fvs(mvs[0], mvs[1], lmax)
fvs

CPU times: user 2min 46s, sys: 296 ms, total: 2min 47s
Wall time: 1min 10s


(array([0.61105855, 1.18990493, 1.3201296 , 1.56128225, 0.35433486,
        0.45480529, 0.94377521, 1.04497377, 1.52727502, 0.18052078,
        1.52730664, 0.96148479, 1.37363873, 1.17207861, 0.46417965,
        0.28099861, 0.36796137, 0.73498645, 1.17830735, 0.93805993,
        0.62122075, 0.74009575, 0.37658607, 1.12888547, 1.34351012,
        1.5123891 , 0.40683886, 1.0940029 , 0.3194123 , 1.16677406,
        1.42419573, 0.34543671, 1.01583102, 1.34500617, 1.13699741,
        1.48061981, 0.52546713, 1.0263482 , 1.43936506, 0.55857656,
        1.20916028, 1.08943552, 1.18560006, 0.9594018 , 0.37270387,
        0.35666562, 0.45447027, 1.2952087 , 0.        , 1.06717354,
        1.16739378, 1.53768153, 1.14798376, 0.93937638, 0.70713563,
        1.51805534, 0.77274541, 0.87658145, 1.43312468, 1.09944312,
        0.50418206, 1.3187383 , 1.15597322, 0.67162902, 1.04976954,
        0.2849867 , 0.82622363, 1.46959896, 1.46223716, 1.42683099,
        1.25008963, 0.63986621, 0.71239712, 1.06