In [1]:
import numpy as np
import os
import sys

In [ ]:
sys.path.append('/home/renan/software/mpsolve/lib')

In [7]:
sys.path.append('/home/renan/software/mpsolve/include')

In [3]:
os.environ["LD_LIBRARY_PATH"] = "/home/renan/software/mpsolve/lib/libmps.so.3:/home/renan/software/gmp/lib:/home/renan/software/mpsolve/lib:/home/renan/software/cfitsio/lib:/home/renan/software/chealpix/lib:/home/renan/software/nlopt/lib64:"

In [1]:
import polymv

ModuleNotFoundError: No module named 'polymv'

In [2]:
alms = np.transpose(np.loadtxt('alm_gsi_lmax800_mc2.dat'))

In [6]:
alms[0]

array([ 0.        , -1.8705763 , 13.66721426, ..., -0.03001029,
       -0.02669888,  0.04738191])

In [4]:
mvs = polymv_C.mvs(alms[0], alms[1], 800)

In [5]:
mvs

(array([2.21299631, 2.48282235, 0.92859634, ..., 0.0757405 , 0.08289888,
        0.10673957]),
 array([-3.06623741, -0.74530784,  0.07535525, ..., -0.03926647,
         2.27862286, -1.06844395]))

In [6]:
mvs

(array([2.21299631, 2.48282235, 0.92859634, ..., 0.0757405 , 0.08289888,
        0.10673957]),
 array([-3.06623741, -0.74530784,  0.07535525, ..., -0.03926647,
         2.27862286, -1.06844395]))

In [9]:
np.savetxt("mvs.dat", np.transpose(mvs) , fmt='%.15f %.15f')

In [7]:
fvs = polymv_C.fvs(mvs[0], mvs[1], 800)

In [9]:
np.savetxt("fvs.dat", np.transpose(fvs) , fmt='%.15f %.15f')

In [21]:
fvs[0][799], fvs[1][799]

(1.3676502268152162, 4.404696905049136)

In [8]:
fvs

(array([1.20020919, 0.78205163, 0.84681032, 0.9128442 , 1.35821343,
        0.94770146, 1.1098899 , 1.00547452, 1.19471704, 1.39136886,
        1.27852656, 1.19050059, 0.74763222, 1.00312101, 1.34784011,
        0.54557809, 1.39910162, 1.36273945, 1.42931057, 1.00820548,
        0.44774081, 1.02521503, 0.26521018, 1.509886  , 0.44864928,
        1.28393528, 1.34272072, 0.95211753, 1.53675946, 0.94720855,
        1.24039998, 0.72699369, 1.25306396, 0.80091877, 0.17930186,
        1.34434308, 0.85104782, 1.48417813, 1.11034849, 0.94644326,
        1.49767064, 1.46067291, 1.01045531, 0.88303979, 1.1787587 ,
        0.92089984, 1.42587454, 0.52090701, 0.73653155, 0.75086788,
        0.48901794, 1.43279789, 1.35132143, 1.28623702, 0.26635718,
        1.53371927, 1.18809344, 0.56529241, 1.3756879 , 1.26081105,
        1.24621149, 1.06624357, 0.81602214, 0.7301043 , 1.29398261,
        0.86909332, 1.32896314, 1.56012523, 0.41791551, 1.2382145 ,
        1.40956759, 1.29198606, 0.97933628, 1.24