Tested on a DELL XPS 8900 with 6th Generation Intel® Core™ i5-6400 Processor (2.7 GHz up to 3.3 GHz, 6MB Cache)

In [8]:
import numpy as np
import healpy as hp

from polymv import polymv

In [9]:
help(polymv)

Help on module polymv.polymv in polymv:

NAME
    polymv.polymv

FUNCTIONS
    frechet_single(theta, phi)
        Compute a single Fréchet vector for an arbitrary set of polar unit vectors.
        Parameters:
            theta: polar angles in radians
            phi:   azimuthal angles in radians
        Returns:
            (out_theta, out_phi): scalar floats
    
    fvs(input1, input2, LMAX)
        Get Fréchet mean vectors in spherical coordinates for a multipole given a map based on lmax.
        
        Parameters:
            input1 (float): Multipole vector theta coordinate.
            input2 (float): Multipole vector phi coordinate.
            LMAX (int): Maximum l value to compute the Fréchet mean.
        
        Returns:
            array: An array for all Fréchet mean based on all multipole vectors in spherical coordinates (theta, phi) from l=2 to lmax.
    
    mvs(input1, input2, LMAX)
        Get multipole vectors in spherical coordinates for a multipole given a m

In [10]:
lmax = 300

In [11]:
%%time
np.random.seed(1234)
alm = hp.synalm(np.ones(2000), lmax=lmax)
alm = np.column_stack([alm.real, alm.imag])
alm

CPU times: user 10.7 ms, sys: 2.01 ms, total: 12.8 ms
Wall time: 12 ms


array([[ 0.47143516,  0.        ],
       [-1.19097569,  0.        ],
       [ 1.43270697,  0.        ],
       ...,
       [ 0.00791896,  0.22230707],
       [-0.29469227, -0.78186176],
       [ 0.59740953,  2.26668483]], shape=(45451, 2))

In [12]:
%%time
mvs = polymv.mvs(alm[:, 0], alm[:, 1], lmax)
mvs

CPU times: user 20.4 s, sys: 1.21 s, total: 21.6 s
Wall time: 5.61 s


(array([2.25239681, 2.0910002 , 0.88919585, ..., 0.12264154, 0.13963065,
        0.12990636], shape=(90298,)),
 array([-2.61799303,  1.13457204,  0.52359962, ...,  1.07193691,
         2.70851409, -1.57573244], shape=(90298,)))

In [13]:
%%time
fvs = polymv.fvs(mvs[0], mvs[1], lmax)
fvs

CPU times: user 9.78 s, sys: 29.5 ms, total: 9.81 s
Wall time: 2.4 s


(array([1.16138262, 1.5581846 , 0.61080621, 1.54710228, 1.51663615,
        1.05655232, 0.16026941, 1.33610933, 0.68367916, 1.33932534,
        0.12715105, 1.52551034, 1.20620241, 0.99834852, 1.25037396,
        1.09800048, 0.91173609, 1.55710672, 1.08964612, 1.35244527,
        1.32271432, 1.06491847, 0.3996814 , 0.78912806, 0.3478085 ,
        0.86464589, 0.66750436, 0.48263779, 0.68331015, 1.38340854,
        1.46518816, 1.34535026, 0.26527724, 0.5396022 , 1.29215776,
        0.92295333, 1.46800113, 1.43129235, 0.93066837, 1.31757418,
        0.72671077, 1.22311096, 1.47516656, 1.18410305, 0.93117992,
        1.25805133, 1.01280127, 0.84814968, 0.52339356, 1.39413179,
        0.30326111, 0.90041477, 0.94076773, 1.39461224, 0.78303435,
        1.38626843, 1.10871502, 0.46562401, 1.10202084, 0.73347925,
        0.81674357, 0.37674649, 0.84224343, 1.52432363, 1.27653107,
        0.75117735, 0.28640796, 1.25774912, 0.51756309, 0.45128421,
        0.97063675, 0.0962387 , 1.42099259, 0.95

In [14]:
%%time
fvs_single = polymv.frechet_single(fvs[0], fvs[1])
fvs_single

CPU times: user 625 ms, sys: 2.98 ms, total: 628 ms
Wall time: 626 ms


DEBUG guess: theta=0.0654 phi=5.5074


(0.06568088531166144, 5.508930217625435)